---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	orchestrator_agent(orchestrator_agent)
	plan_executor_agent(plan_executor_agent)
	user_input_agent(user_input_agent)
	general_agent(general_agent)
	tts_agent(tts_agent)
	test_agent(test_agent)
	__end__([<p>__end__</p>]):::last
	__start__ --> user_input_agent;
	general_agent --> tts_agent;
	orchestrator_agent --> plan_executor_agent;
	plan_executor_agent -.-> general_agent;
	plan_executor_agent -.-> orchestrator_agent;
	plan_executor_agent -.-> test_agent;
	test_agent --> plan_executor_agent;
	user_input_agent --> orchestrator_agent;
	tts_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
